[package]
name = "wglib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.4.0"
gfa = "0.10.1"
bv = "0.11.1"
proptest = "1.3.1"
simple-sds = { path = "tools/simple-sds" }
